<a href="https://colab.research.google.com/github/channel1umut-lang/Python-for-Data-Science/blob/main/0004_Intro_to_Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
grades = {"Atil":50, "James":60, "Lans":30} #dictionary

In [ ]:
pd.Series(grades) #series can help list them

Atil     50
James    60
Lans     30
dtype: int64

In [ ]:
names = "Atil","James","Lans"
grades = [50,60,30]

In [ ]:
pd.Series(names)

0     Atil
1    James
2     Lans
dtype: object

In [ ]:
pd.Series(grades)

0    50
1    60
2    30
dtype: int64

In [ ]:
pd.Series(grades,names)

Atil     50
James    60
Lans     30
dtype: int64

In [ ]:
pd.Series(data=grades,index=names)

Atil     50
James    60
Lans     30
dtype: int64

In [ ]:
#with numpy

In [ ]:
nump_array = np.array([10,20,30,40,50])

In [ ]:
pd.Series(nump_array)

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [ ]:
# arithmatic

In [ ]:
contest_result = pd.Series(data = [10,5,100], index = ["Atil", "James", "Lars"])

In [ ]:
contest_result2 = pd.Series(data = [20,50,10], index = ["Atil", "James", "Lars"])

In [ ]:
contest_result

Atil      10
James      5
Lars     100
dtype: int64

In [ ]:
contest_result["Atil"]

np.int64(10)

In [ ]:
contest_result2["James"]

np.int64(50)

In [ ]:
final_result = contest_result + contest_result2

In [ ]:
final_result # it understand that it need to sum datas itself

Atil      30
James     55
Lars     110
dtype: int64

In [ ]:
contest_result * contest_result2

Atil      200
James     250
Lars     1000
dtype: int64

In [ ]:
different_series = pd.Series([20,30,40,50],["a","b","c","d"])

In [ ]:
different_series

a    20
b    30
c    40
d    50
dtype: int64

In [ ]:
different_series2 = pd.Series([10,50,3,1],["a","c","f","g"])

In [ ]:
different_series + different_series2 #sadece olan indexleri topldi the rest is NaN. NaN stands for “Not a Number,” which represents unrepresentable numeric values in Python

a    30.0
b     NaN
c    90.0
d     NaN
f     NaN
g     NaN
dtype: float64