<a href="https://colab.research.google.com/github/channel1umut-lang/Python-for-Data-Science/blob/main/0005_IntroToDataFrame.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
data = np.random.randn(4,3)

In [ ]:
data

array([[-0.53517531, -0.63252049,  1.09049994],
       [-2.62497483, -0.08435594,  1.61651266],
       [-0.7016534 ,  1.47431089,  0.26877905],
       [ 1.77374169,  1.79910644, -0.69328423]])

In [ ]:
dataFrame = pd.DataFrame(data) #normal dataya cevirdik

In [ ]:
dataFrame

          0         1         2
0 -0.535175 -0.632520  1.090500
1 -2.624975 -0.084356  1.616513
2 -0.701653  1.474311  0.268779
3  1.773742  1.799106 -0.693284

In [ ]:
type(dataFrame)

pandas.core.frame.DataFrame

In [ ]:
dataFrame[0]

0   -0.223460
1   -0.919069
2    1.281447
3   -0.434437
Name: 0, dtype: float64

In [ ]:
type(dataFrame[0])

pandas.core.series.Series

In [ ]:
new_df = pd.DataFrame(data, index=["A","B","C","D"], columns=["Maas","Yas","Calisma Saati"])

In [ ]:
new_df

       Maas       Yas  Calisma Saati
A -0.223460  0.529775       1.218726
B -0.919069 -1.771888      -0.861245
C  1.281447  0.865609       0.425683
D -0.434437 -1.274397       1.106765

In [ ]:
new_df ["Yas"]

A    0.529775
B   -1.771888
C    0.865609
D   -1.274397
Name: Yas, dtype: float64

In [ ]:
new_df ["Maas"]

A   -0.223460
B   -0.919069
C    1.281447
D   -0.434437
Name: Maas, dtype: float64

In [ ]:
new_df [["Yas","Maas"]] # to see more than one column

        Yas      Maas
A  0.529775 -0.223460
B -1.771888 -0.919069
C  0.865609  1.281447
D -1.274397 -0.434437

In [ ]:
new_df.loc ["A"]

Maas            -0.223460
Yas              0.529775
Calisma Saati    1.218726
Name: A, dtype: float64

In [ ]:
new_df.loc [["A","B"]] # to see more than one row

       Maas       Yas  Calisma Saati
A -0.223460  0.529775       1.218726
B -0.919069 -1.771888      -0.861245

In [ ]:
new_df.iloc[2] #brings the row considering the index

Maas             1.281447
Yas              0.865609
Calisma Saati    0.425683
Name: C, dtype: float64

In [ ]:
new_df

       Maas       Yas  Calisma Saati
A -0.223460  0.529775       1.218726
B -0.919069 -1.771888      -0.861245
C  1.281447  0.865609       0.425683
D -0.434437 -1.274397       1.106765

In [ ]:
new_df.iloc[:,2] # ":" main that select the all rows. ",2" show the column i have choosen, We wanted to call columns via indexes

A    1.090500
B    1.616513
C    0.268779
D   -0.693284
Name: Calisma Saati, dtype: float64

In [ ]:
#data manipulation

In [ ]:
new_df

       Maas       Yas  Calisma Saati
A -0.535175 -0.632520       1.090500
B -2.624975 -0.084356       1.616513
C -0.701653  1.474311       0.268779
D  1.773742  1.799106      -0.693284

In [ ]:
new_df ["Ekstra"] = 10 #Added column

In [ ]:
new_df

       Maas       Yas  Calisma Saati  Ekstra
A -0.535175 -0.632520       1.090500      10
B -2.624975 -0.084356       1.616513      10
C -0.701653  1.474311       0.268779      10
D  1.773742  1.799106      -0.693284      10

In [ ]:
new_df.drop ("Ekstra", axis=1) # "axis = 1" = columns, "axis=0" = rows

       Maas       Yas  Calisma Saati
A -0.535175 -0.632520       1.090500
B -2.624975 -0.084356       1.616513
C -0.701653  1.474311       0.268779
D  1.773742  1.799106      -0.693284

In [ ]:
new_df.drop("D", axis=0) #deleting one row

       Maas       Yas  Calisma Saati
A -0.535175 -0.632520       1.090500
B -2.624975 -0.084356       1.616513
C -0.701653  1.474311       0.268779

In [ ]:
new_df  #for to drope we should write new_df = new_df.drop("D", axis=0)

       Maas       Yas  Calisma Saati  Ekstra
A -0.223460  0.529775       1.218726      10
B -0.919069 -1.771888      -0.861245      10
C  1.281447  0.865609       0.425683      10
D -0.434437 -1.274397       1.106765      10

In [ ]:
new_df.drop("Ekstra", axis=1, inplace=True) # another way to drop, inplace main that do it inside of table and do not build another df

In [ ]:
new_df

       Maas       Yas  Calisma Saati
A -0.535175 -0.632520       1.090500
B -2.624975 -0.084356       1.616513
C -0.701653  1.474311       0.268779
D  1.773742  1.799106      -0.693284

In [ ]:
new_df ["D"] = 10 #let add same value as a column

In [ ]:
new_df

       Maas       Yas  Calisma Saati   D
A -0.535175 -0.632520       1.090500  10
B -2.624975 -0.084356       1.616513  10
C -0.701653  1.474311       0.268779  10
D  1.773742  1.799106      -0.693284  10

In [ ]:
new_df.drop("D") # it deleted only row because the value of the axis itself is "0". Note : Deleting rows is more common than deleting columns!!

       Maas       Yas  Calisma Saati   D
A -0.223460  0.529775       1.218726  10
B -0.919069 -1.771888      -0.861245  10
C  1.281447  0.865609       0.425683  10

In [ ]:
new_df.drop("D", axis=1 , inplace = True)

In [ ]:
new_df

       Maas       Yas  Calisma Saati
A -0.223460  0.529775       1.218726
B -0.919069 -1.771888      -0.861245
C  1.281447  0.865609       0.425683
D -0.434437 -1.274397       1.106765

In [ ]:
new_df.drop("D", axis=0)

       Maas       Yas  Calisma Saati
A -0.223460  0.529775       1.218726
B -0.919069 -1.771888      -0.861245
C  1.281447  0.865609       0.425683

In [ ]:
new_df

       Maas       Yas  Calisma Saati
A -0.223460  0.529775       1.218726
B -0.919069 -1.771888      -0.861245
C  1.281447  0.865609       0.425683
D -0.434437 -1.274397       1.106765

In [ ]:
new_df.loc["A"]

Maas            -0.223460
Yas              0.529775
Calisma Saati    1.218726
Name: A, dtype: float64

In [ ]:
new_df.loc["A"]["Maas"] #A nin maasini gormek

np.float64(-0.22345976218473235)

In [ ]:
new_df.loc["A","Maas"] #A nin maasini gormek

np.float64(-0.22345976218473235)

In [ ]:
new_df.loc[["A","B"],["Maas","Yas"]]

       Maas       Yas
A -0.223460  0.529775
B -0.919069 -1.771888

In [ ]:
new_df.loc["A","Maas"] = 100

In [ ]:
new_df

         Maas       Yas  Calisma Saati
A  100.000000  0.529775       1.218726
B   -0.919069 -1.771888      -0.861245
C    1.281447  0.865609       0.425683
D   -0.434437 -1.274397       1.106765

In [ ]:
new_df.loc[["A","B"],["Maas","Yas"]] = 50,80 #spesifik degerleri degistirme

In [ ]:
new_df

        Maas        Yas  Calisma Saati
A  50.000000  80.000000       1.218726
B  50.000000  80.000000      -0.861245
C   1.281447   0.865609       0.425683
D  -0.434437  -1.274397       1.106765

In [ ]:
new_df>0

    Maas    Yas  Calisma Saati
A   True   True           True
B   True   True          False
C   True   True           True
D  False  False           True

In [ ]:
boolen_frame = new_df>0

In [ ]:
new_df[boolen_frame]

        Maas        Yas  Calisma Saati
A  50.000000  80.000000       1.218726
B  50.000000  80.000000            NaN
C   1.281447   0.865609       0.425683
D        NaN        NaN       1.106765

In [ ]:
new_df

        Maas        Yas  Calisma Saati
A  50.000000  80.000000       1.218726
B  50.000000  80.000000      -0.861245
C   1.281447   0.865609       0.425683
D  -0.434437  -1.274397       1.106765

In [ ]:
new_df[new_df["Maas"]>1] #sadece Maas kolonunda maasi birden buyuk olan rowlari gostermesini istedik

        Maas        Yas  Calisma Saati
A  50.000000  80.000000       1.218726
B  50.000000  80.000000      -0.861245
C   1.281447   0.865609       0.425683

In [ ]:
new_df[new_df["Yas"]<0]

       Maas       Yas  Calisma Saati
D -0.434437 -1.274397       1.106765

In [ ]:
#with index logic

In [ ]:
new_df

        Maas        Yas  Calisma Saati
A  50.000000  80.000000       1.218726
B  50.000000  80.000000      -0.861245
C   1.281447   0.865609       0.425683
D  -0.434437  -1.274397       1.106765

In [ ]:
new_df.reset_index()

  index       Maas        Yas  Calisma Saati
0     A  50.000000  80.000000       1.218726
1     B  50.000000  80.000000      -0.861245
2     C   1.281447   0.865609       0.425683
3     D  -0.434437  -1.274397       1.106765

In [ ]:
reset_frame = new_df.reset_index()

In [ ]:
reset_frame

  index       Maas        Yas  Calisma Saati
0     A  50.000000  80.000000       1.218726
1     B  50.000000  80.000000      -0.861245
2     C   1.281447   0.865609       0.425683
3     D  -0.434437  -1.274397       1.106765

In [ ]:
#reset_frame.loc["Atil"] does not work beacuse we have indexes anymore

In [ ]:
reset_frame.loc[0]

index                   A
Maas                 50.0
Yas                  80.0
Calisma Saati    1.218726
Name: 0, dtype: object

In [ ]:
new_indeces = ["Ahmet","Burak","Ceren","Deniz"]

In [ ]:
new_df["Newindex"] = new_indeces

In [ ]:
new_df

        Maas        Yas  Calisma Saati Newindex
A  50.000000  80.000000       1.218726    Ahmet
B  50.000000  80.000000      -0.861245    Burak
C   1.281447   0.865609       0.425683    Ceren
D  -0.434437  -1.274397       1.106765    Deniz

In [ ]:
new_df.set_index("Newindex", inplace=True) # kolonu indexe cevirdi.

In [ ]:
new_df

               Maas        Yas  Calisma Saati
Newindex
Ahmet     50.000000  80.000000       1.218726
Burak     50.000000  80.000000      -0.861245
Ceren      1.281447   0.865609       0.425683
Deniz     -0.434437  -1.274397       1.106765

In [ ]:
new_df.loc["Ahmet"]

Maas             50.000000
Yas              80.000000
Calisma Saati     1.218726
Name: Ahmet, dtype: float64

In [ ]:
#multi index

In [ ]:
first_index = ["Simpson","Simpson","Simpson","South Park","South Park","South Park"]

In [ ]:
inner_index = ["Homer","Bart","Marge","Cartman","Kenny","Kyle"]

In [ ]:
zipped_index = list(zip(first_index,inner_index))

In [ ]:
zipped_index

[('Simpson', 'Homer'),
 ('Simpson', 'Bart'),
 ('Simpson', 'Marge'),
 ('South Park', 'Cartman'),
 ('South Park', 'Kenny'),
 ('South Park', 'Kyle')]

In [ ]:
zipped_index = pd.MultiIndex.from_tuples(zipped_index) # birden fazla index varsa bunu getirmek icin

In [ ]:
zipped_index

MultiIndex([(   'Simpson',   'Homer'),
            (   'Simpson',    'Bart'),
            (   'Simpson',   'Marge'),
            ('South Park', 'Cartman'),
            ('South Park',   'Kenny'),
            ('South Park',    'Kyle')],
           )

In [ ]:
sample_values = np.ones((6,2))

In [ ]:
big_df = pd.DataFrame(sample_values, index=zipped_index, columns=["Maas","Yas"])

In [ ]:
big_df

                    Maas  Yas
Simpson    Homer     1.0  1.0
           Bart      1.0  1.0
           Marge     1.0  1.0
South Park Cartman   1.0  1.0
           Kenny     1.0  1.0
           Kyle      1.0  1.0

In [ ]:
big_df["Maas"]

Simpson     Homer      1.0
            Bart       1.0
            Marge      1.0
South Park  Cartman    1.0
            Kenny      1.0
            Kyle       1.0
Name: Maas, dtype: float64

In [ ]:
#big_df.loc["Homer"] does not work because it is multiple index
big_df.loc["Simpson"]

       Maas  Yas
Homer   1.0  1.0
Bart    1.0  1.0
Marge   1.0  1.0

In [ ]:
big_df.loc["Simpson"].loc["Homer"]

Maas    1.0
Yas     1.0
Name: Homer, dtype: float64