<a href="https://colab.research.google.com/github/channel1umut-lang/Python-for-Data-Science/blob/main/0006_DataFrameOperations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive #taking data from drive to the colab
drive.mount('/content/drive') #mounting data

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
path = "/content/drive/MyDrive/Colab Notebooks/DataSets/6-weather.xlsx" # path shows wehere is the datas locations
weather_df = pd.read_excel(path) # reading data

In [ ]:
weather_df

   Istanbul  New York  Amsterdam  Paris
0        20        10         15     12
1        21        10         17     14
2        20        13         18     15
3        22        14         19     18
4        25        15         15     20
5        28        13         22     16
6        15        12         15     15
7        20        15         14     14
8        22        16         16     16

In [ ]:
weather_df.head(6) #shows first 5 rows

   Istanbul  New York  Amsterdam  Paris
0        20        10         15     12
1        21        10         17     14
2        20        13         18     15
3        22        14         19     18
4        25        15         15     20
5        28        13         22     16

In [ ]:
weather_df.tail() #shows last 5 rows

   Istanbul  New York  Amsterdam  Paris
4        25        15         15     20
5        28        13         22     16
6        15        12         15     15
7        20        15         14     14
8        22        16         16     16

In [ ]:
weather_df.info() #non-null main that there is no unfilled data in this datasets

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9 entries, 0 to 8
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Istanbul   9 non-null      int64
 1   New York   9 non-null      int64
 2   Amsterdam  9 non-null      int64
 3   Paris      9 non-null      int64
dtypes: int64(4)
memory usage: 420.0 bytes

In [ ]:
weather_df.describe() #shows statistical datas

        Istanbul   New York  Amsterdam      Paris
count   9.000000   9.000000   9.000000   9.000000
mean   21.444444  13.111111  16.777778  15.555556
std     3.609401   2.147350   2.538591   2.351123
min    15.000000  10.000000  14.000000  12.000000
25%    20.000000  12.000000  15.000000  14.000000
50%    21.000000  13.000000  16.000000  15.000000
75%    22.000000  15.000000  18.000000  16.000000
max    28.000000  16.000000  22.000000  20.000000

In [ ]:
weather_df.count() # shows how many data exist

Istanbul     9
New York     9
Amsterdam    9
Paris        9
dtype: int64

In [ ]:
weather_df.isna() # shows whether exist miss data

   Istanbul  New York  Amsterdam  Paris
0     False     False      False  False
1     False     False      False  False
2     False     False      False  False
3     False     False      False  False
4     False     False      False  False
5     False     False      False  False
6     False     False      False  False
7     False     False      False  False
8     False     False      False  False

In [ ]:
#working with missing data

In [ ]:
weather_na_df = pd.read_excel("/content/drive/MyDrive/Colab Notebooks/DataSets/6-weatherna.xlsx")

In [ ]:
weather_na_df

   Istanbul  New York  Amsterdam  Paris
0      20.0      10.0       15.0   12.0
1      21.0      10.0        NaN   14.0
2       NaN      13.0       18.0   15.0
3      22.0      14.0       19.0   18.0
4      25.0      15.0       15.0   20.0
5      28.0       NaN       22.0    NaN
6      15.0      12.0       15.0   15.0
7      20.0      15.0       14.0    NaN
8      22.0      16.0       16.0    NaN

In [ ]:
weather_na_df.isna()

   Istanbul  New York  Amsterdam  Paris
0     False     False      False  False
1     False     False       True  False
2      True     False      False  False
3     False     False      False  False
4     False     False      False  False
5     False      True      False   True
6     False     False      False  False
7     False     False      False   True
8     False     False      False   True

In [ ]:
weather_na_df.describe()

        Istanbul   New York  Amsterdam      Paris
count   8.000000   8.000000   8.000000   6.000000
mean   21.625000  13.125000  16.750000  15.666667
std     3.814914   2.295181   2.712405   2.875181
min    15.000000  10.000000  14.000000  12.000000
25%    20.000000  11.500000  15.000000  14.250000
50%    21.500000  13.500000  15.500000  15.000000
75%    22.750000  15.000000  18.250000  17.250000
max    28.000000  16.000000  22.000000  20.000000

In [ ]:
weather_na_df["Paris"].describe()

count     6.000000
mean     15.666667
std       2.875181
min      12.000000
25%      14.250000
50%      15.000000
75%      17.250000
max      20.000000
Name: Paris, dtype: float64

In [ ]:
weather_na_df["Paris"].count() #shows how many data has

np.int64(6)

In [ ]:
weather_na_df['Amsterdam'].isna()

0    False
1     True
2    False
3    False
4    False
5    False
6    False
7    False
8    False
Name: Amsterdam, dtype: bool

In [ ]:
weather_na_df

   Istanbul  New York  Amsterdam  Paris
0      20.0      10.0       15.0   12.0
1      21.0      10.0        NaN   14.0
2       NaN      13.0       18.0   15.0
3      22.0      14.0       19.0   18.0
4      25.0      15.0       15.0   20.0
5      28.0       NaN       22.0    NaN
6      15.0      12.0       15.0   15.0
7      20.0      15.0       14.0    NaN
8      22.0      16.0       16.0    NaN

In [ ]:
data_na = weather_na_df.dropna() #eger bir row da eksik data varsa bunu direk siler.

In [ ]:
data_na.describe() # eksik datalarin oldugu rowlari sildikten sonra geriye kalan datalarla olusturulan bir tanim listesi

        Istanbul   New York  Amsterdam  Paris
count   4.000000   4.000000        4.0   4.00
mean   20.500000  12.750000       16.0  16.25
std     4.203173   2.217356        2.0   3.50
min    15.000000  10.000000       15.0  12.00
25%    18.750000  11.500000       15.0  14.25
50%    21.000000  13.000000       15.0  16.50
75%    22.750000  14.250000       16.0  18.50
max    25.000000  15.000000       19.0  20.00

In [ ]:
weather_na_df

   Istanbul  New York  Amsterdam  Paris
0      20.0      10.0       15.0   12.0
1      21.0      10.0        NaN   14.0
2       NaN      13.0       18.0   15.0
3      22.0      14.0       19.0   18.0
4      25.0      15.0       15.0   20.0
5      28.0       NaN       22.0    NaN
6      15.0      12.0       15.0   15.0
7      20.0      15.0       14.0    NaN
8      22.0      16.0       16.0    NaN

In [ ]:
weather_na_df.dropna(axis=1) # kolonda eksik bir data varsa o kolunu komple hesaba katmiyor

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4, 5, 6, 7, 8]

In [ ]:
weather_na_df.dropna(axis=0)

   Istanbul  New York  Amsterdam  Paris
0      20.0      10.0       15.0   12.0
3      22.0      14.0       19.0   18.0
4      25.0      15.0       15.0   20.0
6      15.0      12.0       15.0   15.0

In [ ]:
weather_na_df.drop("Paris", axis=1)

   Istanbul  New York  Amsterdam
0      20.0      10.0       15.0
1      21.0      10.0        NaN
2       NaN      13.0       18.0
3      22.0      14.0       19.0
4      25.0      15.0       15.0
5      28.0       NaN       22.0
6      15.0      12.0       15.0
7      20.0      15.0       14.0
8      22.0      16.0       16.0

In [ ]:
weather_na_df.fillna(20) # bos olan herseyi 20 ile doldurdu.

   Istanbul  New York  Amsterdam  Paris
0      20.0      10.0       15.0   12.0
1      21.0      10.0       20.0   14.0
2      20.0      13.0       18.0   15.0
3      22.0      14.0       19.0   18.0
4      25.0      15.0       15.0   20.0
5      28.0      20.0       22.0   20.0
6      15.0      12.0       15.0   15.0
7      20.0      15.0       14.0   20.0
8      22.0      16.0       16.0   20.0

In [ ]:
weather_na_df

   Istanbul  New York  Amsterdam  Paris
0      20.0      10.0       15.0   12.0
1      21.0      10.0        NaN   14.0
2       NaN      13.0       18.0   15.0
3      22.0      14.0       19.0   18.0
4      25.0      15.0       15.0   20.0
5      28.0       NaN       22.0    NaN
6      15.0      12.0       15.0   15.0
7      20.0      15.0       14.0    NaN
8      22.0      16.0       16.0    NaN

In [ ]:
weather_na_df.mean() #average

Istanbul     21.625000
New York     13.125000
Amsterdam    16.750000
Paris        15.666667
dtype: float64

In [ ]:
weather_na_df.median()

Istanbul     21.5
New York     13.5
Amsterdam    15.5
Paris        15.0
dtype: float64

In [ ]:
weather_na_df.fillna(weather_na_df.mean()) #filling with average

   Istanbul  New York  Amsterdam      Paris
0    20.000    10.000      15.00  12.000000
1    21.000    10.000      16.75  14.000000
2    21.625    13.000      18.00  15.000000
3    22.000    14.000      19.00  18.000000
4    25.000    15.000      15.00  20.000000
5    28.000    13.125      22.00  15.666667
6    15.000    12.000      15.00  15.000000
7    20.000    15.000      14.00  15.666667
8    22.000    16.000      16.00  15.666667

In [ ]:
weather_na_df.max()

Istanbul     28.0
New York     16.0
Amsterdam    22.0
Paris        20.0
dtype: float64

In [ ]:
weather_na_df.min()

Istanbul     15.0
New York     10.0
Amsterdam    14.0
Paris        12.0
dtype: float64

In [ ]:
df = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/DataSets/6-employee.csv") #excel dosyasinda yaptigimiz butun islemler burda da gecerli

In [ ]:
df

   Department Employee  Salary  Experience           City
0   Marketing    Emp_1   53483           1       New York
1       Sales    Emp_2   78555           8         Austin
2     Finance    Emp_3   47159           3         Austin
3       Sales    Emp_4  110077           3  San Francisco
4       Sales    Emp_5   65920           1       New York
5          IT    Emp_6   97121          11        Chicago
6     Finance    Emp_7   99479           5        Chicago
7     Finance    Emp_8  119475          10       New York
8     Finance    Emp_9   49457           7        Chicago
9       Sales   Emp_10   96557          10        Chicago
10  Marketing   Emp_11  107189           9       New York
11    Finance   Emp_12  108953          12         Austin
12      Sales   Emp_13   82995           7       New York
13         IT   Emp_14   70757           9         Austin
14  Marketing   Emp_15   39692           8        Chicago
15         IT   Emp_16   75758          12        Chicago
16  Marketing   Emp_17  102409           2        Chicago
17      Sales   Emp_18  101211           1  San Francisco
18         HR   Emp_19   95697           7         Austin
19  Marketing   Emp_20   67065           7  San Francisco
20         IT   Emp_21   62606          14  San Francisco
21      Sales   Emp_22   41534           8       New York
22  Marketing   Emp_23   70397           5  San Francisco
23         HR   Emp_24   31016           3       New York
24         HR   Emp_25  119789          12       New York
25    Finance   Emp_26   85591           8  San Francisco
26    Finance   Emp_27  119812           6         Austin
27         IT   Emp_28   53247          11         Austin
28  Marketing   Emp_29   54300           3         Austin
29  Marketing   Emp_30  104065           1         Austin
30    Finance   Emp_31  112798           3         Austin
31  Marketing   Emp_32   39268           5  San Francisco
32  Marketing   Emp_33  116807          14  San Francisco
33         HR   Emp_34   42185           3        Chicago
34    Finance   Emp_35   93704           1         Austin
35      Sales   Emp_36  116779           5  San Francisco
36    Finance   Emp_37   69099          10        Chicago
37      Sales   Emp_38   38571           7         Austin
38         HR   Emp_39   68044          14       New York
39         IT   Emp_40   81214           7        Chicago
40  Marketing   Emp_41   91228          11  San Francisco
41         HR   Emp_42   78984           9       New York
42  Marketing   Emp_43   70774          10       New York
43         IT   Emp_44   32568          10       New York
44         IT   Emp_45   92592          12        Chicago
45         HR   Emp_46   97563          13  San Francisco
46         IT   Emp_47   32695           3       New York
47      Sales   Emp_48   78190           7         Austin
48         IT   Emp_49   35258           1       New York
49  Marketing   Emp_50  117538           4       New York