<a href="https://colab.research.google.com/github/channel1umut-lang/Python-for-Data-Science/blob/main/0009_DataFrameApply.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
df = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/DataSets/8-apply_function_data.csv")

In [ ]:
df

    Employee_ID     Name Department  Salary  Experience  Performance_Score
0             1    Emp_1  Marketing   82251           6                  5
1             2    Emp_2      Sales   52662          24                  3
2             3    Emp_3    Finance   38392           5                  3
3             4    Emp_4      Sales   60535          20                  3
4             5    Emp_5      Sales  108603           2                  2
..          ...      ...        ...     ...         ...                ...
95           96   Emp_96    Finance   93734          19                  4
96           97   Emp_97      Sales  100467          22                  2
97           98   Emp_98         IT   82662          23                  3
98           99   Emp_99         IT   42688          22                  1
99          100  Emp_100         HR   55342          14                  3

[100 rows x 6 columns]

In [ ]:
df.head()

   Employee_ID   Name Department  Salary  Experience  Performance_Score
0            1  Emp_1  Marketing   82251           6                  5
1            2  Emp_2      Sales   52662          24                  3
2            3  Emp_3    Finance   38392           5                  3
3            4  Emp_4      Sales   60535          20                  3
4            5  Emp_5      Sales  108603           2                  2

In [ ]:
df.tail()

    Employee_ID     Name Department  Salary  Experience  Performance_Score
95           96   Emp_96    Finance   93734          19                  4
96           97   Emp_97      Sales  100467          22                  2
97           98   Emp_98         IT   82662          23                  3
98           99   Emp_99         IT   42688          22                  1
99          100  Emp_100         HR   55342          14                  3

In [ ]:
df.describe()

       Employee_ID         Salary  Experience  Performance_Score
count   100.000000     100.000000  100.000000          100.00000
mean     50.500000   77508.090000   12.090000            3.03000
std      29.011492   26083.327596    7.543939            1.41746
min       1.000000   30206.000000    1.000000            1.00000
25%      25.750000   54347.500000    5.000000            2.00000
50%      50.500000   80932.000000   12.000000            3.00000
75%      75.250000   97620.500000   19.000000            4.00000
max     100.000000  119474.000000   24.000000            5.00000

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 6 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Employee_ID        100 non-null    int64
 1   Name               100 non-null    object
 2   Department         100 non-null    object
 3   Salary             100 non-null    int64
 4   Experience         100 non-null    int64
 5   Performance_Score  100 non-null    int64
dtypes: int64(4), object(2)
memory usage: 4.8+ KB

In [ ]:
df.columns #shows columns

Index(['Employee_ID', 'Name', 'Department', 'Salary', 'Experience',
       'Performance_Score'],
      dtype='object')

In [ ]:
df.columns[1:4]

Index(['Name', 'Department', 'Salary'], dtype='object')

In [ ]:
df[1:20]

    Employee_ID    Name Department  Salary  Experience  Performance_Score
1             2   Emp_2      Sales   52662          24                  3
2             3   Emp_3    Finance   38392           5                  3
3             4   Emp_4      Sales   60535          20                  3
4             5   Emp_5      Sales  108603           2                  2
5             6   Emp_6         IT   82256           6                  5
6             7   Emp_7    Finance  119135          22                  1
7             8   Emp_8    Finance   65222          11                  4
8             9   Emp_9    Finance  107373          16                  1
9            10  Emp_10      Sales  109575          16                  5
10           11  Emp_11  Marketing  114651           1                  4
11           12  Emp_12    Finance   93335           9                  5
12           13  Emp_13      Sales   40965           6                  3
13           14  Emp_14         IT   54538          16                  4
14           15  Emp_15  Marketing  100592           3                  3
15           16  Emp_16         IT   38110          20                  1
16           17  Emp_17  Marketing  109309           4                  1
17           18  Emp_18      Sales   57266          19                  4
18           19  Emp_19         HR   82992           3                  4
19           20  Emp_20  Marketing  112948          19                  5

In [ ]:
def salary_catagory(salary):
  if salary<50000:
    return "Low"
  elif 50000<=salary<100000:
    return "Medium"
  else:
    return "High"

In [ ]:
df["Salary"].apply(salary_catagory)

0     Medium
1     Medium
2        Low
3     Medium
4       High
       ...
95    Medium
96      High
97    Medium
98       Low
99    Medium
Name: Salary, Length: 100, dtype: object

In [ ]:
df["Salary_Catagory"] = df["Salary"].apply(salary_catagory) #added to main df

In [ ]:
df

,Employee_ID,Name,Department,Salary,Experience,Performance_Score,Salary_Catagory
0,1,Emp_1,Marketing,82251,6,5,Medium
1,2,Emp_2,Sales,52662,24,3,Medium
2,3,Emp_3,Finance,38392,5,3,Low
3,4,Emp_4,Sales,60535,20,3,Medium
4,5,Emp_5,Sales,108603,2,2,High
...,...,...,...,...,...,...,...
95,96,Emp_96,Finance,93734,19,4,Medium
96,97,Emp_97,Sales,100467,22,2,High
97,98,Emp_98,IT,82662,23,3,Medium
98,99,Emp_99,IT,42688,22,1,Low
99,100,Emp_100,HR,55342,14,3,Medium

In [ ]:
#if experience > 10 ---> Performance_Score +1 bonus example

In [ ]:
def new(Experience):
  if Experience>10:
    return 1
  else:
    return 0

In [ ]:
df["Experience"].apply(new)

0     0
1     1
2     0
3     1
4     0
     ..
95    1
96    1
97    1
98    1
99    1
Name: Experience, Length: 100, dtype: int64

In [ ]:
df["new_experience"] = df["Experience"].apply(new)

In [ ]:
df

,Employee_ID,Name,Department,Salary,Experience,Performance_Score,Salary_Catagory,new_experience
0,1,Emp_1,Marketing,82251,6,5,Medium,0
1,2,Emp_2,Sales,52662,24,3,Medium,1
2,3,Emp_3,Finance,38392,5,3,Low,0
3,4,Emp_4,Sales,60535,20,3,Medium,1
4,5,Emp_5,Sales,108603,2,2,High,0
...,...,...,...,...,...,...,...,...
95,96,Emp_96,Finance,93734,19,4,Medium,1
96,97,Emp_97,Sales,100467,22,2,High,1
97,98,Emp_98,IT,82662,23,3,Medium,1
98,99,Emp_99,IT,42688,22,1,Low,1
99,100,Emp_100,HR,55342,14,3,Medium,1

In [ ]:
df["New_Performance"] = df["new_experience"] + df["Performance_Score"]

In [ ]:
df

,Employee_ID,Name,Department,Salary,Experience,Performance_Score,Salary_Catagory,new_experience,New_Performance
0,1,Emp_1,Marketing,82251,6,5,Medium,0,5
1,2,Emp_2,Sales,52662,24,3,Medium,1,4
2,3,Emp_3,Finance,38392,5,3,Low,0,3
3,4,Emp_4,Sales,60535,20,3,Medium,1,4
4,5,Emp_5,Sales,108603,2,2,High,0,2
...,...,...,...,...,...,...,...,...,...
95,96,Emp_96,Finance,93734,19,4,Medium,1,5
96,97,Emp_97,Sales,100467,22,2,High,1,3
97,98,Emp_98,IT,82662,23,3,Medium,1,4
98,99,Emp_99,IT,42688,22,1,Low,1,2
99,100,Emp_100,HR,55342,14,3,Medium,1,4

In [ ]:
#another solution

In [ ]:
def adjust_new(row):
  if row["Experience"] > 10:
    return row["Performance_Score"] + 1
  else:
    return row["Performance_Score"]

In [ ]:
df["Adjusted_Score"] = df.apply(adjust_new, axis=1)

In [ ]:
df

,Employee_ID,Name,Department,Salary,Experience,Performance_Score,Salary_Catagory,new_experience,New_Performance,Adjusted_Score
0,1,Emp_1,Marketing,82251,6,5,Medium,0,5,5
1,2,Emp_2,Sales,52662,24,3,Medium,1,4,4
2,3,Emp_3,Finance,38392,5,3,Low,0,3,3
3,4,Emp_4,Sales,60535,20,3,Medium,1,4,4
4,5,Emp_5,Sales,108603,2,2,High,0,2,2
...,...,...,...,...,...,...,...,...,...,...
95,96,Emp_96,Finance,93734,19,4,Medium,1,5,5
96,97,Emp_97,Sales,100467,22,2,High,1,3,3
97,98,Emp_98,IT,82662,23,3,Medium,1,4,4
98,99,Emp_99,IT,42688,22,1,Low,1,2,2
99,100,Emp_100,HR,55342,14,3,Medium,1,4,4

In [ ]:
df["Formatted_name"] = df["Name"].apply(lambda x : x.replace("_"," ")) # alt tire yerine bosluk koydu ancak bunu tek seferligine yapti.

In [ ]:
df

,Employee_ID,Name,Department,Salary,Experience,Performance_Score,Salary_Catagory,new_experience,New_Performance,Adjusted_Score,Formatted_name
0,1,Emp_1,Marketing,82251,6,5,Medium,0,5,5,Emp 1
1,2,Emp_2,Sales,52662,24,3,Medium,1,4,4,Emp 2
2,3,Emp_3,Finance,38392,5,3,Low,0,3,3,Emp 3
3,4,Emp_4,Sales,60535,20,3,Medium,1,4,4,Emp 4
4,5,Emp_5,Sales,108603,2,2,High,0,2,2,Emp 5
...,...,...,...,...,...,...,...,...,...,...,...
95,96,Emp_96,Finance,93734,19,4,Medium,1,5,5,Emp 96
96,97,Emp_97,Sales,100467,22,2,High,1,3,3,Emp 97
97,98,Emp_98,IT,82662,23,3,Medium,1,4,4,Emp 98
98,99,Emp_99,IT,42688,22,1,Low,1,2,2,Emp 99
99,100,Emp_100,HR,55342,14,3,Medium,1,4,4,Emp 100

In [ ]:
df

,Employee_ID,Name,Department,Salary,Experience,Performance_Score,Salary_Catagory,new_experience,New_Performance,Adjusted_Score,Formatted_name
0,1,Emp_1,Marketing,82251,6,5,Medium,0,5,5,Emp 1
1,2,Emp_2,Sales,52662,24,3,Medium,1,4,4,Emp 2
2,3,Emp_3,Finance,38392,5,3,Low,0,3,3,Emp 3
3,4,Emp_4,Sales,60535,20,3,Medium,1,4,4,Emp 4
4,5,Emp_5,Sales,108603,2,2,High,0,2,2,Emp 5
...,...,...,...,...,...,...,...,...,...,...,...
95,96,Emp_96,Finance,93734,19,4,Medium,1,5,5,Emp 96
96,97,Emp_97,Sales,100467,22,2,High,1,3,3,Emp 97
97,98,Emp_98,IT,82662,23,3,Medium,1,4,4,Emp 98
98,99,Emp_99,IT,42688,22,1,Low,1,2,2,Emp 99
99,100,Emp_100,HR,55342,14,3,Medium,1,4,4,Emp 100